//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourceMarketDemo.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrencyExchanx
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public byte SourceCurrencyTypeId { get; set; }
        public byte DestinationCurrencyTypeId { get; set; }
        public decimal SourceAmount { get; set; }
        public decimal DestinationAmount { get; set; }
        public System.DateTime TimeStamp { get; set; }
    
        public virtual CurrencyType CurrencyType_Destination { get; set; }
        public virtual CurrencyType CurrencyType_Source { get; set; }
    }
}
