//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourceMarketDemo.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrencyExchangeRate
    {
        public byte SourceCurrencyId { get; set; }
        public byte DestinationCurrencyId { get; set; }
        public decimal SourceMultiplier { get; set; }
    
        public virtual CurrencyType CurrencyType_Destination { get; set; }
        public virtual CurrencyType CurrencyType_Source { get; set; }
    }
}
