//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourceMarketDemo.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserResourcesPivoted
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public Nullable<long> Fish { get; set; }
        public Nullable<long> Iron { get; set; }
        public Nullable<long> Stone { get; set; }
        public Nullable<long> Wood { get; set; }
    }
}
